version: "3.7"
services:
  app:
    build:
      args:
        user: luiz
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: solluti
    container_name: solluti-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - solluti
  db:
    image: mariadb:10.3
    container_name: solluti-db
    volumes:
      - ./docker-compose/database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: ${DB_CONNECTION}
    ports:
      - 3306:3306
    networks:
      - solluti

  nginx:
    image: nginx:alpine
    container_name: solluti-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - solluti

networks:
  solluti:
    driver: bridge